<?php

/**
 * @file
 * Contains bebinh.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bebinh_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bebinh module.
    case 'help.page.bebinh':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Bebinh customization') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function bebinh_theme() {
  return [
    'bebinh' => [
      'render element' => 'children',
    ],
  ];
}
